### ISSUE TITLE
Modernise the library structure to use `pyproject.toml`?

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/ocf-data-sampler#11]
`ocf-data-sampler` was created from our template which I think is the slightly older way of doing it. We use `requirements.txt` and a `setup.py` file. We should check if the current best-practice is still to use `pyproject.toml` and update to whatever this best-practice is

**Comment by VikramsDataScience** [comment]
Hello there @peterdudfield! I've created a PR for this issue. Would you mind reviewing and letting me know your feedback, please?
