### ISSUE TITLE
enforce dataArray as a type in nwp providers?

### ISSUE THREAD

**Issue by AUdaltsova** [openclimatefix/ocf-data-sampler#32]
## Detailed Description
Responding to [this TODO](https://github.com/openclimatefix/ocf-data-sampler/blob/0a6ad76216580dd868f387e8cc0cadf0341e786e/ocf_data_sampler/load/nwp/providers/ecmwf.py#L36) in ecmwf provider:
```
# TODO: should we control the dtype of the DataArray?
```
I think having "channel" dimension basically does that for you? All providers are guarnteed to have it, and it guarantees that the variables are flattened into a DA

**Comment by dfulu** [comment]
By this comment I actually mean should we lock into `np.float32` or `np.float64` etc of the values in the DataArray. 

Right now I'm leaning towards we shouldn't, although controlling the dtype has bitten us before. For example, the training UKV data is float16 which means that when we have visibility with a value higher than 2*16-1 ~= 65000 it was overflowing to infinity. The visibility is measured in metres and can be more than 65km often enough. We didn't realise this when preparing the training data. Its the reason for this [awful hack in PVNet](https://github.com/openclimatefix/PVNet/blob/main/pvnet/models/multimodal/multimodal.py#L338).

In production we had the UKV data in a different format which wasn't overflowing. Therefore we had to [hack that into the app as well](https://github.com/openclimatefix/pvnet_app/pull/51) to resave the data as float16

**Comment by dfulu** [comment]
change to not planned
