### ISSUE TITLE
Dataloader

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-data-sampler#33]
## Detailed Description
Add a torch dataloader

## Context
- nice to add an example of a dataloader, with batchsize 10

## Possible Implementation
- need to work out how to collate the samples together, to batches

**Comment by dfulu** [comment]
Yeh this should be part of creating the batch saving script which is mentioned in #7. Although currently the equivalent script is [in PVNet](https://github.com/openclimatefix/PVNet/blob/main/scripts/save_batches.py) so maybe it should happen over there?

**Comment by dfulu** [comment]
We also already have the collate function we need to stack the samples together. Its [here](https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/batch/merge_numpy_examples_to_batch.py#L56) in datapipes

**Comment by peterdudfield** [comment]
oh thanks, ill use that collate function

**Comment by peterdudfield** [comment]
Ill ahve a go, as i need it for https://github.com/openclimatefix/pvnet_app/issues/116, and it seemed better to sit here
