### ISSUE TITLE
Move all coordinates to be in ascending order

### ISSUE THREAD

**Issue by dfulu** [openclimatefix/ocf-data-sampler#6]
As default in `ocf_datapipes` the x-axis is in ascending order, and the y-axis is in descending order. This complicates the code in instances where we need to consider the indexes in pixel space, e.g. [everything in this function](https://github.com/openclimatefix/ocf_datapipes/blob/main/ocf_datapipes/select/select_spatial_slice.py#L267).

This will break the compatibility of this library with model already trained with `ocf_datapipes` but I think it is worth it, and this is the logical time to make that break.

**Comment by dfulu** [comment]
@peterdudfield since this conversation is now no longer about the coordinate order, and the compatibility issues mentioned are now listed here openclimatefix/pvnet_app#116, can we close this?

**Comment by peterdudfield** [comment]
yea, did we agree that will will use all coordinates in ascending order? This is done in the load stage?
