### ISSUE TITLE
move batch from ocf-datapipes

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf-data-sampler#65]
I wonder if we should move ocf-datapipes batch into this repo for the moment. 
We could use `Batch.gsp.name` [here](https://github.com/openclimatefix/ocf-data-sampler/blob/main/ocf_data_sampler/numpy_batch/gsp.py#L11) and similar other place, to use a string not a Enum. The Enum we have had problems in the past, when we change the. 

Later on we can add a Batch class with load, save, plot methods e.t.c TODO make issue

**Comment by Sukh-P** [comment]
Happy to pick this one up and create the issue for the Batch class

**Comment by peterdudfield** [comment]
Shall we put this as done and create a new issue saying "create batch class"?
