### ISSUE TITLE
No file found in documentation section in readme

### ISSUE THREAD

**Issue by SophiaLi20** [openclimatefix/ocf-data-sampler#85]
There is no file attached in the documentation section to read a bit about how our torch datasets work in the Readme [here](https://github.com/openclimatefix/ocf-data-sampler/tree/readme-update/ocf_data_sampler/torch_datasets)
below is the screenshot of the result.
![Screenshot (76)](https://github.com/user-attachments/assets/b04e09f8-cf5d-4167-9ea1-a7533e5b2b63)

**Comment by Sukh-P** [comment]
Good catch, do you want to open a PR to fix this @SophiaLi20? I think you can change it to reference the file directly in that  link btw e.g. a link like `[this](ocf_data_sampler/torch_datasets/README.md)`

**Comment by SophiaLi20** [comment]
I’d be happy to work on this and open a PR! However, I don’t currently have the direct link to reference the file. Could you point me in the right direction, or confirm the correct location? Once I have that, I’ll make the change and tag you for review. Thanks for your help @Sukh-P

**Comment by SophiaLi20** [comment]
I’ve tried to open the PR, but it’s asking for collaborator access. Could you please grant me the necessary permissions or guide me on the next steps? Thanks! @Sukh-P

**Comment by Sukh-P** [comment]
@SophiaLi20 have you tried forking the repo first, then making the changes and creating the PR from there? Hopefully that should work, if you have issues then let us know

**Comment by SophiaLi20** [comment]
Hi @Sukh-P,
I have completed the changes and opened a pull request to fix the broken link in the torch datasets documentation. You can check the PR [here](URL to PR). Please let me know if anything needs to be updated or if any further changes are required.

Thank you!
